tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: ORCHESTRA_ROLE
      database: PLATTI_DEMO_DATA
      schema: DEMO_DBT_CORE
      warehouse: ORCHESTRA_WH
